version: "3.8"
services:
  web-server:
    container_name: web-server
    build:
      context: ./sns
      dockerfile: dockerfile
    volumes:
      - ./sns:/srv/server
    restart: always
    expose:
      - "8000"
    networks:
      - nginx_bridge
      - database_bridge
    depends_on:
      - database

  database:
    container_name: database
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - .env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    expose:
      - "3306"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_TCP_PORT=${MYSQL_TCP_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - database_bridge

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - web-server
    networks:
      - nginx_bridge

networks:
  nginx_bridge:
    driver: bridge
  database_bridge:
    driver: bridge