version: "3.8"
services:
  

  # web-server:
  #   container_name: web-server
  #   build:
  #     context: ./sns
  #     dockerfile: dockerfile
  #   volumes:
  #     - ./sns:/srv/server
  #   restart: always
  #   expose:
  #     - "8000"
  #   depends_on:
  #     - database

  # database:
  #   container_name: database
  #   image: mysql:8.0
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   command:
  #     - --character-set-server=utf8mb4
  #     - --collation-server=utf8mb4_unicode_ci
  #   port:
  #     - 3306:3306
  #   volumes:
  #     - ./data/db:/var/lib/mysql
  #   environment:
  #     - MYSQL_DATABASE=${MYSQL_DATABASE}
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  redis:
    container_name: redis
    image: redis:latest
    command: redis-server --port 6379
    ports:
      - 6379:6379
    volumes: 
      - ./cache:/data
  
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes: 
      - ./config/nginx:/etc/nginx/conf.d
    restart: unless-stopped
    ports:
      - 80:80
    # depends_on:
    #   - web-server
    # networks:
    #   - nginx_bridge