version: "3.8"

services:
  app:
    build:
      context: ./sns
      dockerfile: dockerfile
    restart: always
    env_file: 
      - ./sns/.env
    command:
      - bash
      - -c
      - |
        python manage.py wait_for_db -t 120
        python manage.py migrate
        echo yes | python manage.py collectstatic
    stdin_open: true
    volumes:
      - ./sns:/srv/server
    expose:
      - "8000"
    depends_on:
      - database

  database:
    image: mysql:8.0
    env_file:
      - ./sns/.env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql-filse
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_TCP_PORT=${MYSQL_TCP_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  nginx:
    image: nginx:1.21
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - .sns/static:/static
    ports:
      - "80:80"
    depends_on:
      - app

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    command: redis-server --port 6379
    ports:
      - 6379:6379
    volumes: 
      - ./cache:/data
    depends_on:
      - app
